// Upload-time optimization (SCHEMA 13.4): oversized images downsize
// and re-encode as webp; non-images and failures pass through
// untouched. The PNG under test is generated by hand - a real,
// deterministic file with no encoder dependency.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { deflateSync } from 'node:zlib';

import { jpegOrientation, optimizeUpload } from './optimize.ts';

function crc32 ( bytes: Buffer ): number
{
    let crc = 0xFFFFFFFF;

    for ( const byte of bytes )
    {
        crc ^= byte;

        for ( let bit = 0; bit < 8; bit += 1 )
        {
            crc = ( crc >>> 1 ) ^ ( 0xEDB88320 & -( crc & 1 ) );
        }
    }

    return ( crc ^ 0xFFFFFFFF ) >>> 0;
}

function pngChunk ( type: string, data: Buffer ): Buffer
{
    const length = Buffer.alloc( 4 );

    length.writeUInt32BE( data.length );

    const body = Buffer.concat( [ Buffer.from( type, 'latin1' ), data ] );
    const crc = Buffer.alloc( 4 );

    crc.writeUInt32BE( crc32( body ) );
    return Buffer.concat( [ length, body, crc ] );
}

function makePng ( width: number, height: number ): Buffer
{
    const header = Buffer.alloc( 13 );

    header.writeUInt32BE( width, 0 );
    header.writeUInt32BE( height, 4 );
    header[ 8 ] = 8; // bit depth
    header[ 9 ] = 6; // RGBA
    header[ 10 ] = 0;
    header[ 11 ] = 0;
    header[ 12 ] = 0;

    const raw = Buffer.alloc( height * ( width * 4 + 1 ) );

    for ( let y = 0; y < height; y += 1 )
    {
        const row = y * ( width * 4 + 1 );

        for ( let x = 0; x < width; x += 1 )
        {
            // A gradient, so the encoder has real work to do.
            raw[ row + 1 + x * 4 ] = x % 256;
            raw[ row + 2 + x * 4 ] = y % 256;
            raw[ row + 3 + x * 4 ] = ( x + y ) % 256;
            raw[ row + 4 + x * 4 ] = 255;
        }
    }

    return Buffer.concat( [
        Buffer.from( [ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A ] ),
        pngChunk( 'IHDR', header ),
        pngChunk( 'IDAT', deflateSync( raw ) ),
        pngChunk( 'IEND', Buffer.alloc( 0 ) ),
    ] );
}

describe( 'upload-time media optimization', () =>
{
    it( 'downsizes an oversized image and delivers webp', async () =>
    {
        const png = makePng( 200, 100 );
        const optimized = await optimizeUpload( png, '.png', { maxEdge: 64, quality: 75 } );

        assert.equal( optimized.converted, true );
        assert.equal( optimized.extension, '.webp' );
        assert.equal( optimized.bytes.toString( 'latin1', 0, 4 ), 'RIFF' );
        assert.equal( optimized.bytes.toString( 'latin1', 8, 12 ), 'WEBP' );
    } );

    it( 'passes non-images and unparsable bytes through untouched', async () =>
    {
        const svg = Buffer.from( '<svg xmlns="http://www.w3.org/2000/svg"/>' );
        const svgResult = await optimizeUpload( svg, '.svg', { maxEdge: 64, quality: 75 } );

        assert.equal( svgResult.converted, false );
        assert.equal( svgResult.extension, '.svg' );
        assert.ok( svgResult.bytes.equals( svg ) );

        // A .png that is not a PNG must never block the upload.
        const broken = await optimizeUpload( Buffer.from( 'not an image' ), '.png', { maxEdge: 64, quality: 75 } );

        assert.equal( broken.converted, false );
        assert.ok( broken.bytes.equals( Buffer.from( 'not an image' ) ) );
    } );

    it( 'reads EXIF orientation from a JPEG APP1 segment', () =>
    {
        // FFD8, then an APP1 carrying a little-endian TIFF whose IFD0
        // holds orientation (0x0112) = 6.
        const tiff = Buffer.concat( [
            Buffer.from( 'II', 'latin1' ),
            Buffer.from( [ 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00 ] ),
            Buffer.from( [ 0x01, 0x00 ] ),
            Buffer.from( [ 0x12, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00 ] ),
            Buffer.from( [ 0x00, 0x00, 0x00, 0x00 ] ),
        ] );
        const app1Body = Buffer.concat( [ Buffer.from( 'Exif\0\0', 'latin1' ), tiff ] );
        const size = Buffer.alloc( 2 );

        size.writeUInt16BE( app1Body.length + 2 );

        const jpeg = Buffer.concat( [
            Buffer.from( [ 0xFF, 0xD8, 0xFF, 0xE1 ] ),
            size,
            app1Body,
            Buffer.from( [ 0xFF, 0xD9 ] ),
        ] );

        assert.equal( jpegOrientation( jpeg ), 6 );
        assert.equal( jpegOrientation( Buffer.from( 'plainly not a jpeg' ) ), 1 );
    } );
} );
