// Upload-time optimization (SCHEMA 13.4): oversized images downsize
// and re-encode as webp; non-images and failures pass through
// untouched. The PNG under test is generated by hand - a real,
// deterministic file with no encoder dependency.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import decodeWebp from '@jsquash/webp/decode.js';

import { AVATAR_EDGE, jpegOrientation, optimizeAvatar, optimizeUpload } from './optimize.ts';
import { makePng } from './testImages.ts';

describe( 'upload-time media optimization', () =>
{
    it( 'an avatar is center-cropped square, brought to the edge, and delivered webp', async () =>
    {
        const size = async ( bytes: Buffer ): Promise<{ width: number; height: number }> =>
        {
            const image = await decodeWebp( bytes.buffer.slice( bytes.byteOffset, bytes.byteOffset + bytes.byteLength ) as ArrayBuffer ) as { width: number; height: number };

            return { width: image.width, height: image.height };
        };

        const wide = await optimizeAvatar( makePng( 900, 600 ), '.png' );

        assert.equal( wide.extension, '.webp' );
        assert.equal( wide.converted, true );
        assert.deepEqual( await size( wide.bytes ), { width: AVATAR_EDGE, height: AVATAR_EDGE } );
        assert.ok( wide.bytes.length < 40 * 1024, `${wide.bytes.length} bytes` );

        // Smaller than the edge: cropped to its own square, never enlarged.
        const small = await optimizeAvatar( makePng( 120, 180 ), '.png' );

        assert.deepEqual( await size( small.bytes ), { width: 120, height: 120 } );

        // A square webp within the edge is already the delivered shape.
        const again = await optimizeAvatar( wide.bytes, '.webp' );

        assert.equal( again.converted, false );
        assert.equal( again.bytes, wide.bytes );

        // Anything that is not a raster passes through (the route
        // refuses SVG before this is reached).
        const svg = Buffer.from( '<svg xmlns="http://www.w3.org/2000/svg"/>' );

        assert.deepEqual( await optimizeAvatar( svg, '.svg' ), { bytes: svg, extension: '.svg', converted: false } );
    } );

    it( 'downsizes an oversized image and delivers webp', async () =>
    {
        const png = makePng( 200, 100 );
        const optimized = await optimizeUpload( png, '.png', { maxEdge: 64, quality: 75 } );

        assert.equal( optimized.converted, true );
        assert.equal( optimized.extension, '.webp' );
        assert.equal( optimized.bytes.toString( 'latin1', 0, 4 ), 'RIFF' );
        assert.equal( optimized.bytes.toString( 'latin1', 8, 12 ), 'WEBP' );
    } );

    it( 'passes non-images and unparsable bytes through untouched', async () =>
    {
        const svg = Buffer.from( '<svg xmlns="http://www.w3.org/2000/svg"/>' );
        const svgResult = await optimizeUpload( svg, '.svg', { maxEdge: 64, quality: 75 } );

        assert.equal( svgResult.converted, false );
        assert.equal( svgResult.extension, '.svg' );
        assert.ok( svgResult.bytes.equals( svg ) );

        // A .png that is not a PNG must never block the upload.
        const broken = await optimizeUpload( Buffer.from( 'not an image' ), '.png', { maxEdge: 64, quality: 75 } );

        assert.equal( broken.converted, false );
        assert.ok( broken.bytes.equals( Buffer.from( 'not an image' ) ) );
    } );

    it( 'reads EXIF orientation from a JPEG APP1 segment', () =>
    {
        // FFD8, then an APP1 carrying a little-endian TIFF whose IFD0
        // holds orientation (0x0112) = 6.
        const tiff = Buffer.concat( [
            Buffer.from( 'II', 'latin1' ),
            Buffer.from( [ 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00 ] ),
            Buffer.from( [ 0x01, 0x00 ] ),
            Buffer.from( [ 0x12, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00 ] ),
            Buffer.from( [ 0x00, 0x00, 0x00, 0x00 ] ),
        ] );
        const app1Body = Buffer.concat( [ Buffer.from( 'Exif\0\0', 'latin1' ), tiff ] );
        const size = Buffer.alloc( 2 );

        size.writeUInt16BE( app1Body.length + 2 );

        const jpeg = Buffer.concat( [
            Buffer.from( [ 0xFF, 0xD8, 0xFF, 0xE1 ] ),
            size,
            app1Body,
            Buffer.from( [ 0xFF, 0xD9 ] ),
        ] );

        assert.equal( jpegOrientation( jpeg ), 6 );
        assert.equal( jpegOrientation( Buffer.from( 'plainly not a jpeg' ) ), 1 );
    } );
} );
