// Every user-facing word in the chrome, keyed, never inline in markup
// (DEVELOPMENT section 6.1): English is the default catalog, a future
// locale is another catalog with the same keys. The markup reaches
// this through the $t magic registered in app.js.

const english = {
    navPages: 'Pages',
    navCollections: 'Collections',
    navTaxonomies: 'Taxonomies',
    navSiteSettings: 'Settings',
    menuAutoLocked: 'An automatic row: its rule owns the target and the type. Relabel it, reorder it, or delete it.',
    navAllPages: 'All pages',
    navSite: 'Site',
    navTemplates: 'Templates',
    navPartials: 'Partials',
    navNotFound: '404 page',
    notFoundPageNote: 'The site\'s 404 page: served whenever an address does not exist. It has no address of its own, never appears in menus, and is never a draft.',
    navTheme: 'Theme',
    viewPages: 'Pages',
    viewTemplates: 'Templates',
    templatesMeta: '{n} templates',
    templatesMetaOne: '1 template',
    templateDefaultChip: 'default',
    columnName: 'Name',
    columnPages: 'Pages',
    columnItems: 'Items',
    partialsMeta: 'blocks edited once, inserted anywhere',
    menusMeta: 'the link lists navigation components bind',
    partialsEmpty: 'No partials yet. A partial is a set of blocks you edit once and insert into any page.',
    menusEmpty: 'No menus yet. A menu is a list of links a navigation component renders.',
    siteHint: 'Rows open the partial or the menu.',
    addTemplate: 'Add template',
    kindTemplate: 'template',
    columnTitle: 'Title',
    columnAddress: 'Address',
    columnTemplate: 'Template',
    columnDraft: 'Draft',
    pagesMeta: '{n} pages',
    pagesMetaOne: '1 page',
    pagesHint: 'Rows open the page; the template column shows what each page renders through.',
    themeMeta: 'the design tokens every component inherits',
    themeHint: 'Re-theming the site is a token edit; components never hardcode a look.',
    templateSelectLabel: 'Page template',
    templateSelectNote: 'The chrome and layout this page renders through. Its own blocks pour into the template\'s content slot.',
    templateCustom: 'Custom',
    templateCustomNote: 'This page owns its own copy of the template: chrome and layout edit on its canvas, and template edits no longer reach it. Pick a template to return.',
    detachTemplate: 'Make custom',
    editTemplateWord: 'Edit template',
    withContentFrom: '· with content from',
    openThisPage: 'Open this page',
    templateNameLabel: 'Template name',
    templateDefaultNote: 'Every page without a template of its own renders through the default; it keeps its name.',
    templatePagesLine: 'changes reach {n} pages',
    templatePagesLineOne: 'changes reach 1 page',
    templateCanvasNote: 'Everything on this canvas belongs to the template: the header and footer outside the content, the layout around the slot. The page lighting the slot is only a sample.',
    deleteTemplate: 'Delete this template',
    deleteTemplateQuestion: 'Pages using it move to the default template. Nothing else changes.',
    createTemplateTitle: 'New page template',
    createTemplateSub: 'Chrome and layout pages share by name, starting as a copy of the default.',
    newTemplateName: 'Template name',
    createSavedAsTemplate: 'Lives in site.json as “{name}”',
    createConfirmTemplate: 'Create template',
    adoptTemplateForPage: 'Use this template',
    returnPageQuestion: 'This page\'s own chrome and layout are replaced by the template\'s. Its content stays.',
    addPage: 'Add page',
    addCollection: 'Add collection',
    addTaxonomy: 'Add taxonomy',

    viewportGroup: 'Preview viewport',
    viewportDesktop: 'Desktop viewport',
    viewportTablet: 'Tablet viewport',
    viewportPhone: 'Phone viewport',
    notifications: 'Notifications',
    search: 'Search',
    preview: 'Preview',
    save: 'Save',
    saved: 'Saved',
    publish: 'Publish',
    publishing: 'Publishing',
    published: 'Published',
    publishFailed: 'Publish failed',

    tabContent: 'Content',
    tabSettings: 'Settings',
    kindPage: 'page',
    kindComponent: 'component',
    kindCollection: 'collection',
    kindEntry: 'entry',
    kindTaxonomy: 'taxonomy',
    kindTerm: 'term',
    kindSite: 'site',

    addEntry: 'Add entry',
    addTerm: 'Add term',
    columnLayout: 'Layout',
    stateTemplate: 'shared',
    stateCustomized: 'custom',
    termName: 'Name',
    newCollectionName: 'Collection name',
    newTaxonomyName: 'Taxonomy name',
    publicIndex: 'Public index page',
    lockTemplate: 'Lock the layout',
    themeColors: 'Theme colors',

    kindField: 'field',
    surfaceIndex: 'Index page',
    surfaceTemplate: 'Entry layout',
    crumbCollection: 'collection',
    crumbIndex: 'index',
    crumbTemplate: 'layout',
    crumbFields: 'fields',
    withDataFrom: '· with data from',
    editIndexPage: 'Edit index page',
    editEntryTemplate: 'Edit entry layout',
    editFields: 'Edit fields',
    structureLabel: 'Structure',
    fieldsLabel: 'Fields',
    surfaceIndexNote: 'The public listing page every visitor sees.',
    surfaceTemplateNote: 'Changes here restyle every entry that follows the shared layout.',
    surfacePageTemplateNote: 'Changes here reach every page that renders through this template.',
    templateReach: 'changes reach {n} conforming entries',
    templateReachOne: 'changes reach 1 conforming entry',
    viewEntries: 'Entries',
    viewTerms: 'Terms',
    viewLayouts: 'Layouts',
    layoutIndexPage: 'Index page',
    layoutEntryTemplate: 'Entry layout',
    layoutTermTemplate: 'Term layout',
    columnLayout: 'Layout',
    columnPurpose: 'Purpose',
    layoutIndexNote: 'The list of entries at the collection\'s address.',
    layoutEntryTemplateNote: 'How every entry renders, unless it breaks out on its own.',
    layoutTermIndexNote: 'The list of terms at the taxonomy\'s address.',
    layoutTermTemplateNote: 'How every term renders, unless it breaks out on its own.',
    partHeader: 'Header',
    blockContent: 'Content',
    sampleNone: 'None',
    scopePartialNote: 'This is a partial: content edited once and shown wherever it is placed. Edit it on its own canvas.',
    scopeTemplateNote: 'This belongs to the page template: chrome and layout every page through it shares. Edit it on the template canvas.',
    editPartialWord: 'Edit partial',
    discardQuestion: 'Discard what you typed?',
    discardDetail: 'This form has changes that are not saved yet.',
    keepEditing: 'Keep editing',
    discardWord: 'Discard',
    addLayout: 'Add layout',
    createLayoutTitle: 'New layout',
    createLayoutSub: 'An arrangement entries can follow, starting as a copy of the default.',
    newLayoutName: 'Layout name',
    createConfirmLayout: 'Create layout',
    createSavedAsLayout: 'Saved as layouts.{name}',
    deleteLayout: 'Delete this layout',
    layoutFollowers: '{n} entries follow it',
    layoutFollowersOne: '1 entry follows it',
    layoutFollowersTerms: '{n} terms follow it',
    layoutFollowersTermsOne: '1 term follows it',
    termLayoutNote: 'The layout this term\'s page follows.',
    layoutOwnOption: 'custom',
    layoutCanvasNote: 'A named layout is shared: this canvas edits it for every entry that follows it. Its own is this entry alone.',
    kindLayout: 'layout',
    layoutRowNote: 'Entries that follow this layout render through it; edit it on its canvas.',
    layoutRowNoteTerms: 'Terms that follow this layout render through it; edit it on its canvas.',
    userMenu: 'Your menu',
    userLocalProfile: 'local profile · this computer only',
    userSupporterThanks: 'Thank you for being a supporter',
    userManageSubscription: 'Manage subscription',
    supporterIntroTitle: 'Support Casomer',
    supporterIntroBody: 'Casomer is free for personal sites, and it stays that way. Supporters help make that possible with small contributions that keep the work going.',
    supporterIntroBody2: 'In return you get a supporter key, the heart badge on your account & optionally your name on the supporter wall.',
    supporterIntroNote: 'Already supporting? Enter your key and Studio remembers.',
    supporterAlready: 'I already have a key',
    supporterBecome: 'Become a supporter',
    supporterTitle: 'Supporter key',
    supporterSub: 'Thank you. Enter the key from your supporter email.',
    supporterKeyLabel: 'Key',
    supporterKeyPlaceholder: 'Paste your key',
    supporterNote: 'Verifying checks the key with casomer.com. Nothing else leaves this computer.',
    verifyWord: 'Verify',
    supporterKeyProblem: 'That key could not be verified.',
    wallTitle: 'Join the supporter wall?',
    wallSub: 'Supporters can be recognized publicly on casomer.com and in the git repo. This is what would be sent.',
    wallSent: 'What is sent',
    wallImage: 'Image',
    wallImageNote: 'Optional. Your profile avatar.',
    wallName: 'Name',
    wallNamePlaceholder: 'Your name as it should appear',
    wallGithub: 'GitHub handle',
    wallNote: 'Saved to your profile. Not now keeps you on the wall as a private supporter, with no name or link. You can change your mind any time.',
    wallNeeded: 'A name and GitHub handle are needed for the wall.',
    wallDecline: 'Not now',
    wallUpdate: 'Update my entry',
    wallOnNote: 'You are on the wall. Changes here update your entry; leaving keeps you on it as a private supporter, with no name or link.',
    wallLeave: 'Leave the wall',
    wallDetails: 'Wall details',
    wallJoin: 'Add me to the wall',
    userCloudWord: 'Cloud',
    learnMore: 'Learn more',
    licensesNeeded: '{n} needed',
    licensesNoneNeeded: 'None needed',
    licensesNeededOne: 'Needed',
    userProfile: 'Profile',
    // One site per Studio, so one license (Mikey, 2026-09-03); the
    // desktop overview, with many projects, will want the plural.
    userLicenses: 'License',
    userSupport: 'Become a supporter',
    userSupportNote: 'Casomer is free to use personally; a small gift keeps it that way.',
    userCloud: 'Casomer Cloud',
    userCloudNote: 'Work together, publish from anywhere.',
    soonWord: 'Soon',
    appearanceLabel: 'Appearance',
    appearanceSystem: 'System',
    appearanceLight: 'Light',
    appearanceDark: 'Dark',
    profileTitle: 'Your profile',
    profileSub: 'Name and basics, kept on this computer. No account needed.',
    profileName: 'Name',
    profileAvatar: 'Avatar',
    profileAvatarNote: 'A square image; kept in your Casomer config folder.',
    profileEmail: 'Email',
    profileGithub: 'GitHub handle',
    profileGithubPlaceholder: 'octocat',
    profileNote: 'Shown in the menu and used when Studio greets you. Nothing is sent anywhere.',
    userLocal: 'Local editor',
    userNoEmail: 'No email set',
    createIndexLayout: 'Create index page',
    layoutIndexOffNote: 'No public listing yet. Create one to lay it out.',
    editPageWord: 'Edit page',
    createFailed: 'That could not be created.',
    tabEmptyPrompt: 'Select something on the canvas to work with it here.',
    slotNote: 'The content slot. Every page rendering through this template pours its own blocks in here. It stays with the template: it cannot be deleted, though it can sit inside a section.',
    slotSampleLabel: 'Preview with content from',
    partFooter: 'Footer',
    viewFields: 'Fields',
    addTextBlock: 'Text block',
    addRepeatBlock: 'Repeat of this collection',
    selectBlockHint: 'Select a block on the canvas to edit it.',
    boundBadge: 'Entry',
    newTextContent: 'New text',
    closeSurface: 'Done',

    entriesMeta: '{n} entries',
    entriesMetaOne: '1 entry',
    termsMeta: '{n} terms',
    termsMetaOne: '1 term',
    indexAt: 'index at /{stem}/',
    noPublicIndex: 'no public index',
    fieldsMeta: 'the shape every entry shares',
    entriesHint: 'Rows open the entry · nothing selected edits the collection',
    fieldsHint: 'Rows select the field',
    termsHint: 'Rows select · Esc selects the taxonomy',
    settingsHint: 'Changes save as you type',

    repeatShown: '{shown} of {total} entries shown',
    sourceLabel: 'Source',
    componentLabel: 'Component',
    wiringLabel: 'Wiring',
    orderNone: 'Sort order',
    orderAsc: 'Asc',
    orderDesc: 'Desc',
    limitAll: 'All',
    wiringNote: 'Link a field to draw from each item, or enter a value used for every one.',
    pickKindPartial: 'Partial',
    pickKindPartialNote: 'A saved arrangement, reused',
    pickKindPartialUnavailable: 'None saved yet',
    tabUsage: 'In use',
    usageListLabel: 'Used by',
    usageNote: 'Everything that uses this. Click to jump there.',
    usageAreaHeader: 'Header',
    usageAreaFooter: 'Footer',
    usageAreaNotFound: '404 page',
    swapComponentTitle: 'Swap the repeated component',
    swapComponentNote: 'Every item renders through the new component. Linked fields that still fit carry over.',
    notLinked: 'Not linked',
    searchOptions: 'Type to search…',
    linkToField: 'Link to an entry field',
    curatedSource: 'A curated list of entries, edited in the file.',
    repeatTermScope: 'Only entries in this term',
    pickerPlaceholder: 'Add a component…',
    pickerRepeatPlaceholder: 'Repeat entries through…',
    pickerEsc: 'esc',
    pickKindComponent: 'Component',
    pickKindComponentNote: 'One piece of content',
    pickKindSection: 'Section',
    pickKindSectionNote: 'Lays out blocks inside it',
    pickKindRepeat: 'Repeat',
    pickKindRepeatNote: 'One card per entry',
    pickKindRepeatUnavailable: 'Needs a collection first',
    addBlockHere: 'Add a block here',
    addWord: 'Add',
    removeBlock: 'Remove this block',
    moveBlock: 'Drag to move this block',

    fieldName: 'Field name',
    fieldType: 'Type',
    fieldRequired: 'Required',
    fieldHelp: 'Help text',
    copyTagTitle: 'Copy this tag',
    copiedWord: 'Copied',
    fieldHelpPlaceholder: 'Optional — shown under the field',
    fieldColumn: 'Show as a table column',
    fieldReferences: 'References',
    publicTermPages: 'Public term pages',
    hierarchicalLabel: 'Hierarchical',
    hierarchicalNote: 'Terms can nest under other terms - categories with sub-categories.',
    hierarchicalLocked: 'Some terms are nested; turning this off moves them to the top level.',
    hierarchyOffTitle: 'Turn off nesting?',
    hierarchyOffBody: 'Every nested term moves to the top level and its place under its parent is lost. Undo brings the nesting back.',
    hierarchyOffConfirm: 'Turn off',
    termParent: 'Parent term',
    termDescription: 'Description',
    termImage: 'Image',
    editTermTemplate: 'Edit term layout',
    surfaceTermTemplate: 'Term layout',
    surfaceTermTemplateNote: 'Changes here restyle every term page.',
    termAddressLabel: 'Published at {address}',
    termTopLevel: 'Top level',
    fieldTypeFixed: 'This field\'s richer shape is edited in the file.',
    fieldRequiredMark: 'required',
    addField: 'Add field',
    previewEntryPage: 'Preview this entry\'s page',
    editEntryPage: 'Edit this entry\'s page',
    newFieldLabel: 'New field',
    deleteField: 'Remove this field',

    createCollectionTitle: 'New collection',
    createCollectionSub: 'A set of entries that share one layout.',
    createTaxonomyTitle: 'New taxonomy',
    createTaxonomySub: 'A shared vocabulary entries can reference.',
    createNameLabel: 'Name',
    createSavedAs: 'Saved as {file} in your site folder.',
    createPublicIndex: 'Public index page',
    createPublicIndexNote: 'Adds an Index that lists entries at /{stem}/. Turn it off for content that only feeds other pages.',
    createPublicIndexNoteTaxonomy: 'Adds a public page per term. Turn it off for vocabularies that only organize content.',
    createFieldsTitle: 'Fields',
    createFieldsModalNote: 'Title comes built in; add the rest here, or later from the Fields view.',
    createEntriesNext: 'Entries come next \u2014 the table is ready for the first one.',
    createConfirm: 'Create collection',
    createConfirmTaxonomy: 'Create taxonomy',
    createFieldTitle: 'New field',
    fieldNamePlaceholder: 'Field name',
    createPageTitle: 'New page',
    createEntryTitle: 'New entry',
    createTermTitle: 'New term',
    pageTitlePlaceholder: 'Page title',
    entryTitlePlaceholder: 'Entry title',
    termNamePlaceholder: 'Term name',
    createPageConfirm: 'Create page',
    createEntryConfirm: 'Create entry',
    createTermConfirm: 'Create term',
    createPageSlugNote: 'Published at /{slug}/',

    addressOffer: 'Change address to {path}',
    addressTitle: 'Move {old} to {new}?',
    addressBody: 'Everything nested under it - child pages and mounted collections - moves along, and links inside the site follow. The old address stops answering.',
    addressConfirm: 'Change the address',
    deletePage: 'Delete this page',
    deleteConfirmPage: 'Delete page',
    deletePageQuestion: 'Delete this page and its layout?',
    pageNestedNote: 'Pages and collections nested under this one rise a level when it goes.',

    nestUnder: 'Nest under',
    nestTopLevel: 'Top level',
    nestAddressNote: 'Published at /{path}/',
    mountNote: 'Its public pages live under the chosen page\'s address.',
    toggleSection: 'Collapse or expand this section',
    toggleChildren: 'Collapse or expand nested pages',

    nameRequiredTitle: 'A {kind} needs a name',
    nameRequiredBody: 'The name is how it appears everywhere. Restore the previous name, or keep typing a new one.',
    restoreName: 'Restore "{name}"',

    renameOffer: 'Rename file to {file}',
    renameTitle: 'Rename "{old}" to "{new}"?',
    renameBodyCollection: 'Every repeat and reference pointing at it follows. Its public address moves from /{oldStem}/ to /{newStem}/.',
    renameBodyTaxonomy: 'Every field referencing it follows.',
    renameNote: 'One undo reverses the whole move.',
    renameConfirm: 'Rename and update references',

    mediaTitleImage: 'Image',
    mediaTitleFile: 'File',
    mediaDropPrompt: 'Drop a file here, or',
    mediaBrowse: 'browse\u2026',
    mediaReplace: 'Replace\u2026',
    mediaCaption: 'Caption',
    mediaCaptionNote: 'Optional \u2014 shown where the component displays one.',
    mediaAlt: 'Alt text',
    mediaAltHear: 'Screen readers will hear: \u201c{alt}\u201d',
    mediaAltSilent: 'Nothing yet \u2014 screen readers will skip this image.',
    mediaUseImage: 'Use image',
    mediaUseFile: 'Use file',
    mediaUploading: 'Uploading\u2026',
    mediaChooseFile: 'Choose a file\u2026',

    editHeader: 'Edit header',
    editFooter: 'Edit footer',
    editNotFound: 'Edit 404 page',
    surfaceHeader: 'Header',
    surfaceFooter: 'Footer',
    surfaceNotFound: '404 page',
    notFoundNote: 'Shown when a visitor lands on an address that does not exist. Published as /404.html once it has content.',
    regionNote: 'Rendered on every page, outside the content.',
    menusLabel: 'Menus',
    menusMovedNote: 'Menus live in the left nav now: each one is a link tree you can nest and reorder.',
    menuItemPage: 'Page',
    menuItemCustom: 'Custom link',
    addMenuItem: 'Add item',
    menuLabelPlaceholder: 'Label',
    menuLabelFromPage: 'Empty label follows the page title.',
    menuUrlPlaceholder: 'https://\u2026 or /path/',

    navMenus: 'Menus',
    addMenu: 'Add menu',
    createMenuTitle: 'New menu',
    createMenuSub: 'A named tree of links: pages, indexes, custom links, nested freely.',
    newMenuName: 'Menu name',
    createConfirmMenu: 'Create menu',
    createSavedAsMenu: 'Lives in site.json as \u201c{name}\u201d',
    menuMetaOne: '{count} item',
    menuMetaMany: '{count} items',
    menuAddLink: 'Custom link',
    menuAddGroup: 'Heading (not a link)',
    menuRule_topLevelPages: 'Include top-level pages',
    menuRuleNote_topLevelPages: 'Top-level pages join as rows you can reorder and relabel. New pages join automatically; drafts stay out.',
    menuRule_childPages: 'Nest child pages',
    menuRuleNote_childPages: 'Each page item grows a dropdown of its child pages. New children join automatically; drafts stay out.',
    menuRule_collectionIndexes: 'Include collection indexes',
    menuRuleNote_collectionIndexes: 'Public collection index pages join as rows. Collections without a public index stay out.',
    menuRule_taxonomyIndexes: 'Include taxonomy indexes',
    menuRuleNote_taxonomyIndexes: 'Public taxonomy index pages join as rows. Taxonomies without a public index stay out.',
    menuItemsLabel: 'Items',
    menuEmptyNote: 'No items yet. Add pages, indexes, custom links, or headings \u2014 then drag to reorder and use the arrows to nest.',
    menuHint: 'Drag reorders \u00b7 arrows nest and un-nest',
    menuOutdent: 'Un-nest',
    menuIndent: 'Nest under the item above',
    menuItemLabel: 'Label',
    menuItemUrl: 'URL',
    menuGroupWord: 'Heading',
    menuGroupNote: 'A heading, not a link \u2014 its nested items form the dropdown.',
    menuNewGroup: 'New heading',
    menuFamilyNote: 'This item has nested items: they move, indent, and delete with it.',
    menuInspectorNote: 'Select an item to edit its label and target. Nested items render as dropdown families where the site\u2019s menu styles apply.',
    menuTypeLabel: 'Type',
    typePage: 'Page',
    typeCollection: 'Collection index',
    typeTaxonomy: 'Taxonomy index',
    typeCustom: 'Custom link',
    typeHeading: 'Heading',
    mediaLibraryPick: 'Or pick from the library',
    kindPartial: 'partial',
    newTermWord: '+ New term',
    newTermPlaceholder: 'Term name',
    createTermNamed: 'Create “{name}”',
    palettePlaceholder: 'Jump to a page, collection, menu…',
    paletteEmpty: 'Nothing matches.',
    menuAutoChip: 'auto',
    menuAutoNote: 'Auto-included by \u201c{rule}\u201d. Changing its type makes it an ordinary item.',
    menuRenameNote: 'Lowercase, digits, hyphens. Renaming updates every repeat that draws from this menu.',
    deleteMenu: 'Delete menu',
    deleteMenuItem: 'Delete item',
    deleteMenuQuestion: 'Any repeat that draws from this menu will render nothing until it is pointed elsewhere.',
    deleteMenuItemQuestion: 'Its nested items are deleted with it.',
    deleteMenuAutoQuestion: 'This row is auto-included by \u201c{rule}\u201d. Removing it turns that rule off \u2014 its other auto-included rows stay as ordinary items.',
    deleteConfirmMenu: 'Delete menu',
    deleteConfirmMenuItem: 'Delete item',
    deleteConfirmMenuAuto: 'Turn off & remove',
    kindMenu: 'menu',
    kindMenuItem: 'item',
    menuOrderNote: 'Menu order',
    taxonomyOrderNote: 'Term order',

    interpolationHint: 'Embed linked values inline: {example}',
    outlineWord: 'Outline',
    crumbLayout: 'layout',
    surfaceEntryLayout: 'Entry layout',
    layoutSectionLabel: 'Layout',
    layoutStateTemplate: 'Follows the shared layout.',
    layoutStateCustomized: 'Has its own layout - shared layout changes no longer reach it.',
    customizeLayout: 'Customize this entry’s layout',
    customizeLayoutNote: 'Copies the shared layout as a starting point. The entry breaks out of the mold; layout changes stop reaching it.',
    editLayoutWord: 'Edit layout',
    adoptTemplate: 'Return to the shared layout',
    adoptTemplateQuestion: 'Its own layout is discarded; the shared layout takes over again.',
    adoptTemplateConfirm: 'Discard & return',
    morphLinkLabel: 'Morph link',
    morphLinkPlaceholder: 'hero',
    morphLinkNote: 'Give a block on another page the same name and their anchored elements glide into each other during navigation.',
    outlineTitle: 'Heading outline',
    outlineEmpty: 'No headings yet.',
    interpolationMissingAmong: 'Not found: {token}. Available: {paths}',
    interpolationNoScope: 'No {root} here: {token} only resolves on a layout surface.',
    interpolationUseTerm: 'Term pages speak $term, not $entry — try {suggestion}.',
    interpolationUseEntry: 'Entry layouts speak $entry, not $term. Available: {paths}',
    interpolationNotReference: '{token} goes deeper than a plain field allows.',
    fieldDateFormat: 'Date format',
    fieldMultiple: 'Allow multiple',
    filterPlaceholder: 'featured == true',
    filterNote: 'Only entries matching this condition show. Field keys are the words.',
    emptyStateLabel: 'When empty',
    emptyStatePlaceholder: 'Nothing here yet.',
    emptyStateNote: 'Markdown shown when nothing matches. Empty means the repeat renders nothing.',
    addPartial: 'Add partial',
    deletePartial: 'Delete this partial',
    deletePartialQuestion: 'Pages inserting it will report a missing partial until re-pointed.',
    deleteConfirmPartial: 'Delete partial',
    createPartialTitle: 'New partial',
    createPartialSub: 'A reusable set of blocks, edited once and inserted into pages.',
    newPartialName: 'Partial name',
    createConfirmPartial: 'Create partial',
    createSavedAsPartial: 'Lives in site.json as “{name}”',
    partialsGroupWord: 'Partials',
    partialBlockNote: 'This block inserts a site partial. Its content is edited once, on the partial’s own canvas, and every page inserting it follows.',
    editPartialWord: 'Edit',
    editWord: 'Edit',
    pageSizeLabel: 'Entries per page',
    pageSizeNote: 'The index splits into /page/2/ and beyond; a pager appears.',
    pageSizeAll: 'All',
    mediaLibraryLabel: 'Media',
    navMedia: 'Media',
    kindMediaLibrary: 'library',
    mediaUploadWord: 'Upload file',
    mediaCountFiles: '{count} files',
    mediaCountFilesUnused: '{count} files · {unused} unused',
    mediaFileWord: 'File',
    mediaSizeWord: 'Size',
    mediaUsageWord: 'Used',
    mediaLabelWord: 'Name',
    mediaLabelNote: 'The name people see everywhere. The stored file keeps its generated filename.',
    mediaReferencedNote: 'Something still points at this file, so it cannot be removed. The count is how many places reference it.',
    mediaSelectHint: 'Select a file to see its name, size, and usage, or upload a new one.',
    mediaHint: 'Click a file for details · deletes go to the trash first',
    trackMediaLabel: 'Track media in git',
    trackMediaNote: 'Media files version and publish with everything else.',
    trackMediaOffNote: 'Media stays out of git (.gitignore covers media/ and dist/media/). Names and metadata still version — but the files exist only on this machine, and your host needs media delivered another way.',
    mediaViewLibrary: 'Library',
    mediaViewTrash: 'Trash',
    mediaTrashNote: 'Deleted files wait here. Restore them, or delete them forever — the only permanent delete in Studio.',
    mediaTrashEmpty: 'The trash is empty.',
    mediaSearchPlaceholder: 'Search by name…',
    mediaSearchEmpty: 'Nothing matches.',
    mediaBrowseTitle: 'Media library',
    trashUnusedMedia: 'Move unused to trash',
    emptyTrashWord: 'Empty trash',
    moveToTrashWord: 'Move to trash',
    restoreWord: 'Restore',
    deleteForeverWord: 'Delete forever',
    trashAllWord: 'everything in the trash ({count} files)',
    deleteMediaForeverQuestion: 'This deletes the file itself, permanently. Nothing in Studio can bring it back.',
    deleteConfirmMediaForever: 'Delete forever',
    deleteNoteForever: 'The trash was the safety net. A file that was never published exists nowhere else.',
    mediaLibraryNote: 'Everything in media/, with how many places use it. Deleting moves a file to the trash.',
    mediaLibraryEmpty: 'No media yet - images and files land here when you pick them.',
    mediaUnused: 'unused',
    referenceNoOptions: 'Nothing to pick yet.',
    dateFormatLong: 'September 5, 2026',
    dateFormatShort: 'Sep 5, 2026',
    dateFormatIso: 'As stored (2026-09-05)',

    identityLabel: 'Identity',
    siteOriginLabel: 'Site address',
    siteOriginPlaceholder: 'https://example.com',
    siteOriginNote: 'Where the published site lives. A commercial license binds to this address.',
    siteOriginProblem: 'A scheme and host, like https://example.com, with no path.',
    siteNameLabel: 'Site name',
    siteNameNote: 'Shown in Studio and joined into every page title. Empty falls back to the folder name, {folder}.',
    siteIconLabel: 'Site icon',
    siteIconNote: 'One square image; the favicon and app icon derive from it.',
    uploadWord: 'Upload\u2026',
    removeWord: 'Remove',

    declaredUseLabel: 'Declared use',
    usePersonal: 'Personal',
    useCommercial: 'Commercial',
    aboutSite: 'About this site',
    aboutLastPublished: 'Last published',
    neverPublished: 'Never',
    publishingLabel: 'Publishing',
    goLiveGitLabel: 'Pull & push on publish',
    goLiveGitNotSet: 'Not set - saves and publishes stay on this machine.',
    goLiveGitOn: 'On - each publish pulls the latest from the remote, then pushes.',
    goLiveGitOff: 'Off - the remote is kept; publishes stay on this machine.',
    goLiveGitExpired: 'Your GitHub connection has expired. Open Change and connect again; the next publish pushes.',
    reconnectLabel: 'reconnect',
    goLiveUploadLabel: 'Upload site on publish',
    githubOr: 'or connect GitHub in three steps',
    githubStep1: 'Authorize Casomer CMS on GitHub',
    githubStep1Note: 'A code you enter on GitHub. This says the app may act as you; it installs nothing.',
    githubStep2: 'Install the app on the site\'s repository',
    githubStep2Note: 'GitHub asks which repositories the app may touch. Pick this site\'s, or create one first.',
    githubStep3: 'Select a repository',
    githubAuthorized: 'Authorized',
    githubInstall: 'Install on GitHub',
    githubGranted: '{n} repositories granted',
    githubGrantedOne: '1 repository granted',
    githubGrantedNone: 'None granted yet',
    githubConnect: 'Connect GitHub',
    githubConnecting: 'Asking GitHub\u2026',
    githubCodeLead: 'Open GitHub and enter this code:',
    githubOpen: 'Open GitHub',
    githubWaiting: 'Waiting for you to authorize on GitHub\u2026',
    githubConnectedLine: 'Connected to GitHub. Pick the repository publishes go to.',
    githubLoading: 'Fetching your repositories\u2026',
    githubNone: 'GitHub lists the repositories you have granted the Casomer CMS app, and there are none yet. Install the app on your account and pick the repositories it may use, then refresh.',
    githubInstallMore: 'Install the app or grant repositories',
    githubCreateRepo: 'Create a repository on GitHub',
    githubRefresh: 'Refresh',
    githubUse: 'Select',
    githubUnreachable: 'GitHub could not be reached.',
    backupLabel: 'Backup',
    backupNotSet: 'Not set - saves and publishes stay on this machine.',
    connectedLabel: 'connected',
    changeLabel: 'Change',
    saveWord: 'Set',
    remotePlaceholder: 'Git remote URL - empty disconnects',
    goLiveLabel: 'Go live',
    goLiveNote: 'Not set - publish saves versions; nothing is uploaded anywhere yet.',
    goLiveOnNote: 'On - each publish uploads what changed to {target}.',
    goLiveOffNote: 'Off - the details are kept; publish saves versions and backs up, nothing is uploaded.',
    goLiveNoSecret: 'No password or key file yet - open Change and add one.',
    goLiveSetUp: 'Set up',
    deployHost: 'Host',
    deployHostPlaceholder: 'ftp.example.com',
    deployPort: 'Port',
    deployUser: 'User name',
    deployPath: 'Folder on the host',
    deployPathPlaceholder: '/public_html',
    deployPassword: 'Password',
    deployPasswordKeep: 'Leave blank to keep the saved one',
    deployKeyFile: 'Key file (instead of a password)',
    deployKeyFilePlaceholder: 'Path to a private key on this computer, optional',
    deploySecretNote: 'Kept on this computer only, never in the site folder or its backup.',
    deployTest: 'Test connection',
    deployTesting: 'Connecting\u2026',
    deployConnected: 'Connected. {path} holds {n} items.',
    deployConnectedOne: 'Connected. {path} holds 1 item.',
    deployConnectedEmpty: 'Connected. {path} is empty.',
    deployTrustedNew: 'This host\'s key is now trusted; a change to it will be refused.',
    deployForgetKey: 'Forget the trusted host key',
    deploySaveAnyway: 'Save',
    publishUploaded: 'Uploaded {n} files to your host.',
    publishUploadedOne: 'Uploaded 1 file to your host.',
    publishUploadedNone: 'Your host is already current.',
    publishUploadOff: 'Go live is off; nothing was uploaded.',
    publishUploadFailedTitle: 'Saved, not uploaded.',
    publishUploadFailedNote: 'The version is saved and backed up; your host still shows the previous one. The next publish carries it, or upload now.',
    publishUploadNow: 'Upload now',
    publishUploading: 'Uploading\u2026',
    commercialAssentTitle: 'Declare commercial use?',
    commercialAssentBody: 'Commercial production use requires a license once the site goes live; a 14 day evaluation is included.',
    commercialAssentConfirm: 'Declare commercial',

    addColor: 'Add color',
    colorNamePlaceholder: 'token-name',

    typographyLabel: 'Typography',
    typeParagraph: 'Paragraph',
    resourcesLabel: 'Third-party resources',
    resourcesNote: 'Stylesheet URLs - fonts and the like - loaded by every page. https only.',
    addResource: 'Add resource',
    resourcePlaceholder: 'https://fonts.googleapis.com/\u2026',

    layoutTitle: 'Layout',
    layoutGutter: 'Horizontal gutter',
    layoutWidth: 'Content width',
    layoutDerived: 'Default',
    spacingTitle: 'Spacing',

    deleteCollection: 'Delete this collection',
    deleteEntry: 'Delete this entry',
    deleteTaxonomy: 'Delete this taxonomy',
    deleteTerm: 'Delete this term',
    deleteConfirm: 'Delete',
    deleteQuestionNamed: 'Delete "{name}"?',
    deleteConfirmCollection: 'Delete collection',
    deleteConfirmEntry: 'Delete entry',
    deleteConfirmTaxonomy: 'Delete taxonomy',
    deleteConfirmTerm: 'Delete term',
    deleteConfirmField: 'Remove field',
    deleteFieldQuestion: 'Remove this field from every entry?',
    deleteBlockQuestion: 'Remove this block from the layout?',
    deleteNote: 'Publish history keeps every version. This can be restored.',
    deleteCollectionQuestion: 'Delete this collection and every entry in it?',
    deleteEntryQuestion: 'Delete this entry?',
    deleteTaxonomyQuestion: 'Delete this taxonomy and every term in it?',
    deleteTermQuestion: 'Delete this term?',
    blockSection: 'Section',
    sectionInspectorNote: 'How this section arranges its children: the space between and around them, and how they line up.',
    sectionDirection: 'Direction',
    sectionDirectionAutoRow: 'Auto (side by side)',
    sectionDirectionAutoColumn: 'Auto (stacked)',
    sectionDirectionRow: 'Side by side',
    sectionDirectionColumn: 'Stacked',
    sectionDirectionLayer: 'Layered (on top of each other)',
    sectionGap: 'Space between children',
    sectionGapDefault: 'Theme gutter',
    sectionPadding: 'Space inside',
    sectionJustify: 'Distribute along the flow',
    sectionJustify_start: 'Pack to the start',
    sectionJustify_center: 'Pack to the center',
    sectionJustify_end: 'Pack to the end',
    sectionJustify_between: 'Space between',
    sectionJustify_around: 'Space around',
    sectionJustify_evenly: 'Space evenly',
    sectionAlign: 'Line up across the flow',
    sectionAlign_start: 'Start',
    sectionAlign_center: 'Center',
    sectionAlign_end: 'End',
    sectionAlign_stretch: 'Stretch',
    sectionAlign_baseline: 'Baseline',
    sectionWrap: 'Wrap',
    sectionWrapNote: 'Children flow onto a new line when they run out of room.',
    sectionMinHeight: 'Minimum height',
    sectionMinHeight_third: 'A third of the screen',
    sectionMinHeight_half: 'Half the screen',
    sectionMinHeight_screen: 'The whole screen',
    sectionWidth: 'Content width',
    sectionDefault: 'Default',
    sectionNone: 'None',
    layoutCardTitle: 'Layout in its section',
    layoutSize: 'Width',
    layoutSizeShare: 'Share the row equally',
    layoutSize_1_4: 'A quarter',
    layoutSize_1_3: 'A third',
    layoutSize_1_2: 'Half',
    layoutSize_2_3: 'Two thirds',
    layoutSize_3_4: 'Three quarters',
    layoutSize_full: 'Full width',
    layoutSpaceBefore: 'Space before',
    layoutSpaceAfter: 'Space after',
    layoutPull: 'Overlap the previous row',
    layoutHidden: 'Hidden',
    layoutHiddenNote: 'Kept and editable here, left out of the published site.',
    layoutResponsiveNote: 'One of these values changes by breakpoint in the file; the select shows its base value and leaves the rest alone.',
    blockRepeat: 'Repeat',
    backToPage: 'Back to the page',
    addItem: '+ Add item',
    removeItem: 'Remove',
    toggleItem: 'Expand or collapse this item',
    previewTitle: 'Page preview',

    requiredNag: 'Required',
    abandonTitle: '"{name}" is missing required fields',
    abandonMissing: 'Still empty: {fields}',
    abandonNote: 'A draft is kept and editable, but left out of the published site until its Draft switch clears. Discarding removes the entry; undo can bring it back.',
    draftLabel: 'Draft',
    draftNote: 'Kept and editable, left out of the published site.',
    stateDraft: 'draft',
    keepDraft: 'Keep draft',
    discardEntryAction: 'Discard entry',
    saveConfirmTitle: 'Save with incomplete content?',
    saveAnyway: 'Save anyway',
    saveConfirmNote: 'Saving records a version, incomplete or not - publish stays blocked until these are filled in.',
    publishChangedPages: '{n} changed pages',
    publishChangedPagesOne: '1 changed page',
    publishedPages: 'Published {n} pages',
    publishedPagesOne: 'Published 1 page',
    justNow: 'just now',
    publishNothingNew: 'Nothing new to publish',
    publishNothingNewBackedUp: 'Nothing new to publish · pushed',
    publishBackupConflictTitle: 'Saved here, not pushed.',
    publishBackupConflictNote: 'Your remote has changes that conflict with this publish. Nothing was lost: pull and resolve them in git, then publish again.',
    publishBackupExpiredNote: 'Your GitHub connection has expired. Reconnect under Go live in Site settings; the next publish pushes.',
    publishBackupFailedTitle: 'Saved here, not pushed.',
    publishBackupFailedNote: 'Your backup could not be reached, so nothing left this computer and your live site still shows the previous version. The next publish sends everything once you are connected.',
    publishKeyRevokedTitle: 'A key was revoked.',
    graceUnstartedLine: 'Publishing starts this site\'s 14-day evaluation.',
    graceDaysLeft: '{n} days left to license this site.',
    graceDaysLeftOne: '1 day left to license this site.',
    graceExpiredLine: 'The evaluation has ended. Publishing this site needs its license key.',
    graceNote: 'Commercial sites get a 14-day evaluation per site. Publishing works the whole time; after it ends, publishing needs the key.',
    graceExpiredNote: 'Only publishing waits for the key. Building, previewing, and editing are never gated, and the published site out in the world is untouched.',
    licenseKeyLabel: 'License key',
    licenseKeyPlaceholder: 'Paste your license key',
    licenseKeyNote: 'Per-site, never expires. Kept on this computer, never in the site folder. Or re-declare the site if it is genuinely personal.',
    licenseKeyProblem: 'That key could not be saved.',
    getLicense: 'Get a license',
    licenseCardTitle: 'License',
    licenseLicensed: 'Licensed. Never expires.',
    licensedTag: 'Licensed',
    copyKeyWord: 'Copy key',
    licenseTransferCta: 'Request a license transfer',
    licenseTransferSubject: 'License transfer request',
    licenseTransferBody: 'I would like to move my license to a new address.\n\nCurrent address: {host}\nNew address: ',
    licenseLicensedNote: 'Bound to this address, never expires. The key is kept on this computer; publishing never waits.',
    licenseSave: 'Save key',
    licensePersonalLine: 'No license needed.',
    licensePersonalNote: 'This site is declared personal, and personal sites are free forever. If it turns commercial, re-declare it and its license lives here.',
    supporterCardTitle: 'Supporter',
    sponsorCardTitle: 'Sponsorship',
    supportCardTitleBoth: 'Supporter and sponsor',
    supporterCardLead: 'Support Casomer',
    supporterCardNote: 'Personal sites are free forever. Supporters chip in a little to keep the work going, and get the heart badge to show for it.',
    supporterCardThanksNote: 'Your support keeps personal sites free for everyone. The heart badge rides on your account.',
    userSponsorThanks: 'Thank you for being a sponsor',
    sponsorBecome: 'Become a sponsor',
    sponsorIntroTitle: 'Sponsor Casomer',
    sponsorIntroBody: 'Commercial teams can back Casomer\'s development beyond the license. Sponsorship is a conversation, not a checkout; say hello and we will take it from there.',
    sponsorIntroBody2: 'Sponsors get a sponsor key and the star badge on their account.',
    sponsorIntroNote: 'Already sponsoring? Enter your key and Studio remembers.',
    sponsorTitle: 'Sponsor key',
    sponsorSub: 'Thank you. Enter the key from your sponsorship email.',
    sponsorCardThanksNote: 'Your sponsorship backs the work directly. The star badge rides on your account.',
    sponsorLead: 'Sponsor Casomer',
    sponsorNote: 'Commercial teams can back Casomer\'s development beyond the license. Sponsorship is a conversation, not a checkout; say hello and we will take it from there.',
    sponsorCta: 'Email sponsorship@casomer.com',
    publishCountLine: '{n} publishes with this site so far.',
    publishCountLineOne: '1 publish with this site so far.',
    supporterMomentFive: 'Five publishes in. Glad it is working for you. Personal sites are free forever; if Casomer has earned it, you can',
    supporterMomentForty: 'Forty publishes in. This site has come a long way. Personal sites stay free forever; if Casomer has earned its keep, you can',
    supporterMomentLink: 'support development',
    publishFailedTitle: 'Publish did not go through',
    publishFailedNote: 'Nothing was published and nothing was lost. Your edits are safe here.',
    publishFailedStatus: 'The publish was refused (status {status}).',
    publishUnreachable: 'Studio could not reach its own server. Is caso studio still running?',
    closeWord: 'Close',
    publishProblemsTitle: 'Publish needs attention',
    publishProblemsNote: 'Nothing was published. Fill these in and publish again - your edits are safe.',

    statusUnsaved: 'Unsaved changes',
    statusSaved: 'Saved · not published',
    statusUnpushed: 'Published · not backed up',
    discardQuestion: 'Discard unsaved changes?',
    discardNote: 'Everything since the last save will be removed. Undo can bring it back.',
    discardConfirm: 'Discard',
    discardCancel: 'Keep editing',
    cancel: 'Cancel',

    connectionLostTitle: 'Studio lost its connection',
    siteIssuesTitle: 'This site has problems to fix before editing',
    serverUnreachable: 'Studio could not reach its server. Is caso studio still running?',
};

let active = english;

export function t ( key )
{
    return active[ key ] ?? key;
}

export function useCatalog ( catalog )
{
    active = catalog;
}
