// Every user-facing word in the chrome, keyed, never inline in markup
// (DEVELOPMENT section 6.1): English is the default catalog, a future
// locale is another catalog with the same keys. The markup reaches
// this through the $t magic registered in app.js.

const english = {
    navPages: 'Pages',
    navCollections: 'Collections',
    navTaxonomies: 'Taxonomies',
    navSiteSettings: 'Site settings',
    addPage: 'Add page',
    addCollection: 'Add collection',
    addTaxonomy: 'Add taxonomy',

    viewportGroup: 'Preview viewport',
    viewportDesktop: 'Desktop viewport',
    viewportTablet: 'Tablet viewport',
    viewportPhone: 'Phone viewport',
    notifications: 'Notifications',
    search: 'Search',
    preview: 'Preview',
    save: 'Save',
    saved: 'Saved',
    publish: 'Publish',
    publishing: 'Publishing',
    published: 'Published',
    publishFailed: 'Publish failed',

    tabContent: 'Content',
    tabSettings: 'Settings',
    kindPage: 'page',
    kindComponent: 'component',
    kindCollection: 'collection',
    kindEntry: 'entry',
    kindTaxonomy: 'taxonomy',
    kindTerm: 'term',
    kindSite: 'site',

    addEntry: 'Add entry',
    addTerm: 'Add term',
    columnLayout: 'Layout',
    stateTemplate: 'template',
    stateCustomized: 'customized',
    termName: 'Name',
    newCollectionName: 'Collection name',
    newTaxonomyName: 'Taxonomy name',
    publicIndex: 'Public index page',
    lockTemplate: 'Lock the template',
    themeColors: 'Theme colors',

    kindField: 'field',
    surfaceIndex: 'Index page',
    surfaceTemplate: 'Entry template',
    crumbCollection: 'collection',
    crumbIndex: 'index',
    crumbTemplate: 'template',
    crumbFields: 'fields',
    withDataFrom: '· with data from',
    editIndexPage: 'Edit index page',
    editEntryTemplate: 'Edit entry template',
    editFields: 'Edit fields',
    structureLabel: 'Structure',
    fieldsLabel: 'Fields',
    surfaceIndexNote: 'The public listing page every visitor sees.',
    surfaceTemplateNote: 'Changes here restyle every entry that follows the template.',
    templateReach: 'changes reach {n} conforming entries',
    templateReachOne: 'changes reach 1 conforming entry',
    viewEntries: 'Entries',
    viewFields: 'Fields',
    addTextBlock: 'Text block',
    addRepeatBlock: 'Repeat of this collection',
    selectBlockHint: 'Select a block on the canvas to edit it.',
    boundBadge: 'Entry',
    newTextContent: 'New text',
    closeSurface: 'Done',

    entriesMeta: '{n} entries',
    entriesMetaOne: '1 entry',
    termsMeta: '{n} terms',
    termsMetaOne: '1 term',
    indexAt: 'index at /{stem}/',
    noPublicIndex: 'no public index',
    fieldsMeta: 'the shape every entry shares',
    entriesHint: 'Rows open the entry · nothing selected edits the collection',
    fieldsHint: 'Rows select the field',
    termsHint: 'Rows select · Esc selects the taxonomy',
    settingsHint: 'Changes save as you type',

    repeatShown: '{shown} of {total} entries shown',
    sourceLabel: 'Source',
    componentLabel: 'Component',
    wiringLabel: 'Wiring',
    orderNone: 'Sort order',
    orderAsc: 'Asc',
    orderDesc: 'Desc',
    limitAll: 'All',
    wiringNote: 'Link a field to draw from each item, or enter a value used for every one.',
    pickKindPartial: 'Partial',
    pickKindPartialNote: 'A saved arrangement, reused',
    pickKindPartialUnavailable: 'None saved yet',
    tabUsage: 'In use',
    usageListLabel: 'Used by',
    usageNote: 'Everything that uses this. Click to jump there.',
    usageAreaHeader: 'Header',
    usageAreaFooter: 'Footer',
    usageAreaNotFound: '404 page',
    swapComponentTitle: 'Swap the repeated component',
    swapComponentNote: 'Every item renders through the new component. Linked fields that still fit carry over.',
    notLinked: 'Not linked',
    searchOptions: 'Type to search…',
    linkToField: 'Link to an entry field',
    curatedSource: 'A curated list of entries, edited in the file.',
    repeatTermScope: 'Only entries in this term',
    pickerPlaceholder: 'Add a component…',
    pickerRepeatPlaceholder: 'Repeat entries through…',
    pickerEsc: 'esc',
    pickKindComponent: 'Component',
    pickKindComponentNote: 'One piece of content',
    pickKindSection: 'Section',
    pickKindSectionNote: 'Lays out blocks inside it',
    pickKindRepeat: 'Repeat',
    pickKindRepeatNote: 'One card per entry',
    pickKindRepeatUnavailable: 'Needs a collection first',
    addBlockHere: 'Add a block here',
    addWord: 'Add',
    removeBlock: 'Remove this block',

    fieldName: 'Field name',
    fieldType: 'Type',
    fieldRequired: 'Required',
    fieldHelp: 'Help text',
    fieldHelpPlaceholder: 'Optional — shown under the field',
    fieldColumn: 'Show as a table column',
    fieldReferences: 'References',
    publicTermPages: 'Public term pages',
    hierarchicalLabel: 'Hierarchical',
    hierarchicalNote: 'Terms can nest under other terms - categories with sub-categories.',
    hierarchicalLocked: 'Move nested terms to the top level to turn this off.',
    termParent: 'Parent term',
    termDescription: 'Description',
    termImage: 'Image',
    editTermTemplate: 'Edit term template',
    surfaceTermTemplate: 'Term template',
    surfaceTermTemplateNote: 'Changes here restyle every term page.',
    termAddressLabel: 'Published at {address}',
    termTopLevel: 'Top level',
    fieldTypeFixed: 'This field\'s richer shape is edited in the file.',
    fieldRequiredMark: 'required',
    addField: 'Add field',
    previewEntryPage: 'Preview this entry\'s page',
    editEntryPage: 'Edit this entry\'s page',
    newFieldLabel: 'New field',
    deleteField: 'Remove this field',

    createCollectionTitle: 'New collection',
    createCollectionSub: 'A set of entries that share one template.',
    createTaxonomyTitle: 'New taxonomy',
    createTaxonomySub: 'A shared vocabulary entries can reference.',
    createNameLabel: 'Name',
    createSavedAs: 'Saved as {file} in your site folder.',
    createPublicIndex: 'Public index page',
    createPublicIndexNote: 'Adds an Index that lists entries at /{stem}/. Turn it off for content that only feeds other pages.',
    createPublicIndexNoteTaxonomy: 'Adds a public page per term. Turn it off for vocabularies that only organize content.',
    createFieldsNext: 'Fields come next — start with a title, grow as you go.',
    createConfirm: 'Create collection',
    createConfirmTaxonomy: 'Create taxonomy',
    createFieldTitle: 'New field',
    fieldNamePlaceholder: 'Field name',
    createPageTitle: 'New page',
    createEntryTitle: 'New entry',
    createTermTitle: 'New term',
    pageTitlePlaceholder: 'Page title',
    entryTitlePlaceholder: 'Entry title',
    termNamePlaceholder: 'Term name',
    createPageConfirm: 'Create page',
    createEntryConfirm: 'Create entry',
    createTermConfirm: 'Create term',
    createPageSlugNote: 'Published at /{slug}/',

    addressOffer: 'Change address to {path}',
    addressTitle: 'Move {old} to {new}?',
    addressBody: 'Everything nested under it - child pages and mounted collections - moves along, and links inside the site follow. The old address stops answering.',
    addressConfirm: 'Change the address',
    deletePage: 'Delete this page',
    deleteConfirmPage: 'Delete page',
    deletePageQuestion: 'Delete this page and its layout?',
    pageNestedNote: 'Pages or collections are nested under this one. Move them first.',

    nestUnder: 'Nest under',
    nestTopLevel: 'Top level',
    nestAddressNote: 'Published at /{path}/',
    mountNote: 'Its public pages live under the chosen page\'s address.',
    toggleSection: 'Collapse or expand this section',
    toggleChildren: 'Collapse or expand nested pages',

    nameRequiredTitle: 'A {kind} needs a name',
    nameRequiredBody: 'The name is how it appears everywhere. Restore the previous name, or keep typing a new one.',
    restoreName: 'Restore "{name}"',

    renameOffer: 'Rename file to {file}',
    renameTitle: 'Rename "{old}" to "{new}"?',
    renameBodyCollection: 'Every repeat and reference pointing at it follows. Its public address moves from /{oldStem}/ to /{newStem}/.',
    renameBodyTaxonomy: 'Every field referencing it follows.',
    renameNote: 'One undo reverses the whole move.',
    renameConfirm: 'Rename and update references',

    mediaTitleImage: 'Image',
    mediaTitleFile: 'File',
    mediaDropPrompt: 'Drop a file here, or',
    mediaBrowse: 'browse\u2026',
    mediaReplace: 'Replace\u2026',
    mediaCaption: 'Caption',
    mediaCaptionNote: 'Optional \u2014 shown where the component displays one.',
    mediaAlt: 'Alt text',
    mediaAltHear: 'Screen readers will hear: \u201c{alt}\u201d',
    mediaAltSilent: 'Nothing yet \u2014 screen readers will skip this image.',
    mediaUseImage: 'Use image',
    mediaUseFile: 'Use file',
    mediaUploading: 'Uploading\u2026',
    mediaChooseFile: 'Choose a file\u2026',

    editHeader: 'Edit header',
    editFooter: 'Edit footer',
    editNotFound: 'Edit 404 page',
    surfaceHeader: 'Header',
    surfaceFooter: 'Footer',
    surfaceNotFound: '404 page',
    notFoundNote: 'Shown when a visitor lands on an address that does not exist. Published as /404.html once it has content.',
    regionNote: 'Rendered on every page, outside the content.',
    menusLabel: 'Menus',
    menusMovedNote: 'Menus live in the left nav now: each one is a link tree you can nest and reorder.',
    menuItemPage: 'Page',
    menuItemCustom: 'Custom link',
    addMenuItem: 'Add item',
    menuLabelPlaceholder: 'Label',
    menuLabelFromPage: 'Empty label follows the page title.',
    menuUrlPlaceholder: 'https://\u2026 or /path/',

    navMenus: 'Menus',
    addMenu: 'Add menu',
    createMenuTitle: 'New menu',
    createMenuSub: 'A named tree of links: pages, indexes, custom links, nested freely.',
    newMenuName: 'Menu name',
    createConfirmMenu: 'Create menu',
    createSavedAsMenu: 'Lives in site.json as \u201c{name}\u201d',
    menuMetaOne: '{count} item',
    menuMetaMany: '{count} items',
    menuAddLink: 'Custom link',
    menuAddGroup: 'Heading (not a link)',
    menuRule_topLevelPages: 'Include top-level pages',
    menuRuleNote_topLevelPages: 'Top-level pages join as rows you can reorder and relabel. New pages join automatically; drafts stay out.',
    menuRule_childPages: 'Nest child pages',
    menuRuleNote_childPages: 'Each page item grows a dropdown of its child pages. New children join automatically; drafts stay out.',
    menuRule_collectionIndexes: 'Include collection indexes',
    menuRuleNote_collectionIndexes: 'Public collection index pages join as rows. Collections without a public index stay out.',
    menuRule_taxonomyIndexes: 'Include taxonomy indexes',
    menuRuleNote_taxonomyIndexes: 'Public taxonomy index pages join as rows. Taxonomies without a public index stay out.',
    menuItemsLabel: 'Items',
    menuEmptyNote: 'No items yet. Add pages, indexes, custom links, or headings \u2014 then drag to reorder and use the arrows to nest.',
    menuHint: 'Drag reorders \u00b7 arrows nest and un-nest',
    menuOutdent: 'Un-nest',
    menuIndent: 'Nest under the item above',
    menuItemLabel: 'Label',
    menuItemUrl: 'URL',
    menuGroupWord: 'Heading',
    menuGroupNote: 'A heading, not a link \u2014 its nested items form the dropdown.',
    menuNewGroup: 'New heading',
    menuFamilyNote: 'This item has nested items: they move, indent, and delete with it.',
    menuInspectorNote: 'Select an item to edit its label and target. Nested items render as dropdown families where the site\u2019s menu styles apply.',
    menuTypeLabel: 'Type',
    typePage: 'Page',
    typeCollection: 'Collection index',
    typeTaxonomy: 'Taxonomy index',
    typeCustom: 'Custom link',
    typeHeading: 'Heading',
    mediaLibraryPick: 'Or pick from the library',
    kindPartial: 'partial',
    newTermWord: '+ New term',
    newTermPlaceholder: 'Term name',
    createTermNamed: 'Create “{name}”',
    palettePlaceholder: 'Jump to a page, collection, menu…',
    paletteEmpty: 'Nothing matches.',
    themeToDark: 'Switch to dark mode',
    themeToLight: 'Switch to light mode',
    menuAutoChip: 'auto',
    menuAutoNote: 'Auto-included by \u201c{rule}\u201d. Changing its type makes it an ordinary item.',
    menuRenameNote: 'Lowercase, digits, hyphens. Renaming updates every repeat that draws from this menu.',
    deleteMenu: 'Delete menu',
    deleteMenuItem: 'Delete item',
    deleteMenuQuestion: 'Any repeat that draws from this menu will render nothing until it is pointed elsewhere.',
    deleteMenuItemQuestion: 'Its nested items are deleted with it.',
    deleteMenuAutoQuestion: 'This row is auto-included by \u201c{rule}\u201d. Removing it turns that rule off \u2014 its other auto-included rows stay as ordinary items.',
    deleteConfirmMenu: 'Delete menu',
    deleteConfirmMenuItem: 'Delete item',
    deleteConfirmMenuAuto: 'Turn off & remove',
    kindMenu: 'menu',
    kindMenuItem: 'item',
    menuOrderNote: 'Menu order',
    taxonomyOrderNote: 'Term order',

    interpolationHint: 'Embed linked values inline: {example}',
    outlineWord: 'Outline',
    crumbLayout: 'layout',
    surfaceEntryLayout: 'Entry layout',
    layoutSectionLabel: 'Layout',
    layoutStateTemplate: 'Follows the shared template.',
    layoutStateCustomized: 'Has its own layout - template changes no longer reach it.',
    customizeLayout: 'Customize this entry’s layout',
    customizeLayoutNote: 'Copies the template as a starting point. The entry breaks out of the mold; template changes stop reaching it.',
    editLayoutWord: 'Edit layout',
    adoptTemplate: 'Return to the template',
    adoptTemplateQuestion: 'Its own layout is discarded; the shared template takes over again.',
    adoptTemplateConfirm: 'Discard & return',
    morphLinkLabel: 'Morph link',
    morphLinkPlaceholder: 'hero',
    morphLinkNote: 'Give a block on another page the same name and their anchored elements glide into each other during navigation.',
    outlineTitle: 'Heading outline',
    outlineEmpty: 'No headings yet.',
    interpolationMissingAmong: 'Not found: {token}. Available: {paths}',
    interpolationNoScope: 'No {root} here: {token} only resolves on a template surface.',
    interpolationUseTerm: 'Term pages speak $term, not $entry — try {suggestion}.',
    interpolationUseEntry: 'Entry templates speak $entry, not $term. Available: {paths}',
    interpolationNotReference: '{token} goes deeper than a plain field allows.',
    fieldDateFormat: 'Date format',
    fieldMultiple: 'Allow multiple',
    filterPlaceholder: 'featured == true',
    filterNote: 'Only entries matching this condition show. Field keys are the words.',
    emptyStateLabel: 'When empty',
    emptyStatePlaceholder: 'Nothing here yet.',
    emptyStateNote: 'Markdown shown when nothing matches. Empty means the repeat renders nothing.',
    addPartial: 'Add partial',
    deletePartial: 'Delete this partial',
    deletePartialQuestion: 'Pages inserting it will report a missing partial until re-pointed.',
    deleteConfirmPartial: 'Delete partial',
    createPartialTitle: 'New partial',
    createPartialSub: 'A reusable set of blocks, edited once and inserted into pages.',
    newPartialName: 'Partial name',
    createConfirmPartial: 'Create partial',
    createSavedAsPartial: 'Lives in site.json as “{name}”',
    partialsGroupWord: 'Partials',
    partialBlockNote: 'This block inserts a site partial. Its content is edited once, on the partial’s own canvas, and every page inserting it follows.',
    editPartialWord: 'Edit',
    editWord: 'Edit',
    pageSizeLabel: 'Entries per page',
    pageSizeNote: 'The index splits into /page/2/ and beyond; a pager appears.',
    pageSizeAll: 'All',
    mediaLibraryLabel: 'Media',
    navMedia: 'Media',
    kindMediaLibrary: 'library',
    mediaUploadWord: 'Upload file',
    mediaCountFiles: '{count} files',
    mediaCountFilesUnused: '{count} files · {unused} unused',
    mediaFileWord: 'File',
    mediaSizeWord: 'Size',
    mediaUsageWord: 'Used',
    mediaLabelWord: 'Name',
    mediaLabelNote: 'The name people see everywhere. The stored file keeps its generated filename.',
    mediaReferencedNote: 'Something still points at this file, so it cannot be removed. The count is how many places reference it.',
    mediaSelectHint: 'Select a file to see its name, size, and usage, or upload a new one.',
    mediaHint: 'Click a file for details · deletes go to the trash first',
    trackMediaLabel: 'Track media in git',
    trackMediaNote: 'Media files version and publish with everything else.',
    trackMediaOffNote: 'Media stays out of git (.gitignore covers media/ and dist/media/). Names and metadata still version — but the files exist only on this machine, and your host needs media delivered another way.',
    mediaViewLibrary: 'Library',
    mediaViewTrash: 'Trash',
    mediaTrashNote: 'Deleted files wait here. Restore them, or delete them forever — the only permanent delete in Studio.',
    mediaTrashEmpty: 'The trash is empty.',
    mediaSearchPlaceholder: 'Search by name…',
    mediaSearchEmpty: 'Nothing matches.',
    mediaBrowseTitle: 'Media library',
    trashUnusedMedia: 'Move unused to trash',
    emptyTrashWord: 'Empty trash',
    moveToTrashWord: 'Move to trash',
    restoreWord: 'Restore',
    deleteForeverWord: 'Delete forever',
    trashAllWord: 'everything in the trash ({count} files)',
    deleteMediaForeverQuestion: 'This deletes the file itself, permanently. Nothing in Studio can bring it back.',
    deleteConfirmMediaForever: 'Delete forever',
    deleteNoteForever: 'The trash was the safety net. A file that was never published exists nowhere else.',
    mediaLibraryNote: 'Everything in media/, with how many places use it. Deleting moves a file to the trash.',
    mediaLibraryEmpty: 'No media yet - images and files land here when you pick them.',
    mediaUnused: 'unused',
    referenceNoOptions: 'Nothing to pick yet.',
    dateFormatLong: 'September 5, 2026',
    dateFormatShort: 'Sep 5, 2026',
    dateFormatIso: 'As stored (2026-09-05)',

    identityLabel: 'Identity',
    siteNameLabel: 'Site name',
    siteNameNote: 'Shown in Studio and joined into every page title. Empty falls back to the folder name, {folder}.',
    siteIconLabel: 'Site icon',
    siteIconNote: 'One square image; the favicon and app icon derive from it.',
    uploadWord: 'Upload\u2026',
    removeWord: 'Remove',

    declaredUseLabel: 'Declared use',
    usePersonal: 'Personal',
    useCommercial: 'Commercial',
    aboutSite: 'About this site',
    aboutLastPublished: 'Last published',
    neverPublished: 'Never',
    publishingLabel: 'Publishing',
    backupLabel: 'Backup',
    backupNotSet: 'Not set - saves and publishes stay on this machine.',
    connectedLabel: 'connected',
    changeLabel: 'Change',
    saveWord: 'Set',
    remotePlaceholder: 'Git remote URL - empty disconnects',
    goLiveLabel: 'Go live',
    goLiveNote: 'Not set - publish saves versions; nothing is uploaded anywhere yet.',
    commercialAssentTitle: 'Declare commercial use?',
    commercialAssentBody: 'Commercial production use requires a license once the site goes live; a 14 day evaluation is included.',
    commercialAssentConfirm: 'Declare commercial',

    addColor: 'Add color',
    colorNamePlaceholder: 'token-name',

    typographyLabel: 'Typography',
    typeParagraph: 'Paragraph',
    resourcesLabel: 'Third-party resources',
    resourcesNote: 'Stylesheet URLs - fonts and the like - loaded by every page. https only.',
    addResource: 'Add resource',
    resourcePlaceholder: 'https://fonts.googleapis.com/\u2026',

    layoutTitle: 'Layout',
    layoutGutter: 'Horizontal gutter',
    layoutWidth: 'Content width',
    layoutDerived: 'Default',
    spacingTitle: 'Spacing',

    deleteCollection: 'Delete this collection',
    deleteEntry: 'Delete this entry',
    deleteTaxonomy: 'Delete this taxonomy',
    deleteTerm: 'Delete this term',
    deleteConfirm: 'Delete',
    deleteQuestionNamed: 'Delete "{name}"?',
    deleteConfirmCollection: 'Delete collection',
    deleteConfirmEntry: 'Delete entry',
    deleteConfirmTaxonomy: 'Delete taxonomy',
    deleteConfirmTerm: 'Delete term',
    deleteConfirmField: 'Remove field',
    deleteFieldQuestion: 'Remove this field from every entry?',
    deleteBlockQuestion: 'Remove this block from the layout?',
    deleteNote: 'Publish history keeps every version. This can be restored.',
    deleteCollectionQuestion: 'Delete this collection and every entry in it?',
    deleteEntryQuestion: 'Delete this entry?',
    deleteTaxonomyQuestion: 'Delete this taxonomy and every term in it?',
    deleteTermQuestion: 'Delete this term?',
    blockSection: 'Section',
    blockRepeat: 'Repeat',
    backToPage: 'Back to the page',
    addItem: '+ Add item',
    removeItem: 'Remove',
    toggleItem: 'Expand or collapse this item',
    previewTitle: 'Page preview',

    requiredNag: 'Required',
    abandonTitle: '"{name}" is missing required fields',
    abandonMissing: 'Still empty: {fields}',
    abandonNote: 'A draft is kept and editable, but left out of the published site until its Draft switch clears. Discarding removes the entry; undo can bring it back.',
    draftLabel: 'Draft',
    draftNote: 'Kept and editable, left out of the published site.',
    stateDraft: 'draft',
    keepDraft: 'Keep draft',
    discardEntryAction: 'Discard entry',
    saveConfirmTitle: 'Save with incomplete content?',
    saveAnyway: 'Save anyway',
    saveConfirmNote: 'Saving records a version, incomplete or not - publish stays blocked until these are filled in.',
    publishProblemsTitle: 'Publish needs attention',
    publishProblemsNote: 'Nothing was published. Fill these in and publish again - your edits are safe.',

    statusUnsaved: 'Unsaved changes',
    statusSaved: 'Saved · not published',
    discardQuestion: 'Discard unsaved changes?',
    discardNote: 'Everything since the last save will be removed. Undo can bring it back.',
    discardConfirm: 'Discard',
    discardCancel: 'Keep editing',
    cancel: 'Cancel',

    connectionLostTitle: 'Studio lost its connection',
    siteIssuesTitle: 'This site has problems to fix before editing',
    serverUnreachable: 'Studio could not reach its server. Is caso studio still running?',
};

let active = english;

export function t ( key )
{
    return active[ key ] ?? key;
}

export function useCatalog ( catalog )
{
    active = catalog;
}
